### ISSUE TITLE
[PLGWOOS-266] CRITICAL Uncaught Error: Call to a member function get_status() on boolean 

### ISSUE THREAD

**Issue by mcjefix** [MultiSafepay/WooCommerce#1]
`CRITICAL Uncaught Error: Call to a member function get_status() on boolean in ../wp-content/plugins/WooCommerce-3.2.0/includes/classes/MultiSafepay/Gateways.php:563`.

We are getting this error since the WooCommerce 3.5.6 release. Also we've been seeing double reductions of our stocks for some orders.

**Comment by Jasper-MultiSafepay** [comment]
@mcjefix 
Could you send an email to techsupport@multisafepay.com so we check which signals have been sent?
