### ISSUE TITLE
Puli Factory is not available

### ISSUE THREAD

**Issue by arnogregorian** [MultiSafepay/WooCommerce#10]
After updating to the latest version I get the following error when opening the checkout page:

`Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - Puli Factory is not available - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Http\Discovery\Strategy\CommonClassesStrategy::symfonyPsr18Instantiate, GuzzleHttp\Client, Http\Discovery\Strategy\CommonClassesStrategy::buzzInstantiate. - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: . in /srv/users/********/apps/********/public/wp-content/plugins/multisafepay/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41 Stack trace: #0 /srv/users/********/apps/********/public/wp-content/plugins/multisafepay/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array) #1 / in /srv/users/********/apps/********/public/wp-content/plugins/multisafepay/vendor/php-http/discovery/src/Psr18ClientDiscovery.php on line 27`

Is this an error on our side or something in the plugin, reverted back to 3.8 for now, thanks in advance!

**Comment by Daniel-MultiSafepay** [comment]
Hello @arnogregorian.

Please, could you tell us if you upgrade the plugin from the repository; or using Wordpress?

We need this reply to investigate more about this issue. 

Thanks.

**Comment by arnogregorian** [comment]
I used WordPress, simple update through the WordPress plugins page.

**Comment by Daniel-MultiSafepay** [comment]
Thanks for reply. 

We are currently investigating this issue. Hope to get back as soon as possible with a solution.

**Comment by Jasper-MultiSafepay** [comment]
@arnogregorian 
Could you provide us with a list of the installed plugins, so we can find if there is a conflict?

**Comment by Jasper-MultiSafepay** [comment]
@arnogregorian 
We just released 4.1.4 which should fix your issue.
Please let us know if this will solve your reported issue.

**Comment by arnogregorian** [comment]
Fixed it, thanks!

**Comment by Jasper-MultiSafepay** [comment]
That's great to hear.
I will close this issue, but let us know if you have more feedback.
