### ISSUE TITLE
Order item price is ignored, causing incorrect amounts to be invoiced

### ISSUE THREAD

**Issue by Stoux** [MultiSafepay/WooCommerce#11]
Hi,

We've updated to version 4.x (currently on 4.1.2) and noticed that any modifications done to the price of an order item are completely ignored by the plugin. This block of code causes our problems: https://github.com/MultiSafepay/WooCommerce/blob/master/src/Services/ShoppingCartService.php#L79-L88

We've patched it out by replacing the whole block with just the `$product_price = (float) $item->get_total() / (int) $item->get_quantity();` line.

See attached images:
![image](https://user-images.githubusercontent.com/4819194/108855472-56dbb080-75e9-11eb-9e7d-30c9276f8c58.png)
![image](https://user-images.githubusercontent.com/4819194/108855479-58a57400-75e9-11eb-80c3-cd61e64d974b.png)

**Comment by Daniel-MultiSafepay** [comment]
Hello @Stoux 

Thanks for reporting. This issue should be solved now with the latest release (version 4.1.5).

Could you upgrade to latest version 4.1.5 in a safe environment and test. If everything works properly now, you should be able to continue upgrading the plugin safely without introduce new changes by your self.
