### ISSUE TITLE
Uncaught Error: Class 

### ISSUE THREAD

**Issue by NoemiNL** [MultiSafepay/woocommerce#17]
Downloaded and updated to version 4.16.0 today after vulnerability found in 4.15, but after this we get the following error:

`Uncaught Error: Class 'MultiSafepay\WooCommerce\Settings\SettingsFields' not found in /var/www/vhosts/DOMAIN.nl/httpdocs/wp-content/plugins/multisafepay/src/Settings/SettingsController.php:199
Stack trace:
#0 /var/www/vhosts/DOMAIN.nl/httpdocs/wp-includes/class-wp-hook.php(307): MultiSafepay\WooCommerce\Settings\SettingsController->register_common_settings()
#1 /var/www/vhosts/DOMAIN.nl/httpdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /var/www/vhosts/DOMAIN.nl/httpdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#3 /var/www/vhosts/DOMAIN.nl/httpdocs/wp-admin/admin-ajax.php(45): do_action()
#4 {main}
  thrown`

The customer relies on this plugin to work correctly for their shop payments, hopefully this can be resolved soon.

**Comment by Daniel-MultiSafepay** [comment]
Hello @NoemiNL.

Thanks for your report and reach us. unfortunately, I can't reproduce the error but I have some ideas and comments: 

More or less the error says: 

"SettingsFields not found in /wp-content/plugins/multisafepay/src/Settings/SettingsController.php:199"

However, both classes are under the same namespace:

"namespace MultiSafepay\WooCommerce\Settings;"

And technically that error should not be happening, and the only issue I can imagine at this moment is that something went wrong when you updated the plugin, without replace properly the vendor directory which contains the autoloader classes.  

Could you try to re-download the latest version of the plugin from the following URL

https://github.com/MultiSafepay/woocommerce/releases/download/4.16.0/Plugin_WooCommerce_4.16.0.zip

After that reinstall using the plugin uploader tool from Wordpress; in Wordpress Admin > Plugins > Add New > Select the .zip file and click in "Install Now".

Could you let me know your results? 
I will be waiting your feedback. 

Thanks again.

**Comment by NoemiNL** [comment]
Hi Daniel,

Looks like you are right, I replaced the installed version this morning once again and up until now no errors.
Thank you for the swift reply and action!

Hopefully WordPress.org approves the plugin again soon.

Regards,
Noemi
