### ISSUE TITLE
[PLGWOOS-203] Payment Customer Message not translatable (WPML)

### ISSUE THREAD

**Issue by jeroenlammerts** [MultiSafepay/WooCommerce#2]
When using WPML the Customer Message is not translatable.

$gateway->get_title() is called directly in payment-method.php and the translations works, the description only shows in the default language.

It has to do with the following code, I'm not sure how to fix this.

includes/classes/MultiSafepay/Gateway/Abstract.php line 225
payment_fields method

![Capture 2019-07-11 at 11 21 59](https://user-images.githubusercontent.com/4282711/61038904-1f959d00-a3ce-11e9-83b7-b6eb73eb9a3f.png)

**Comment by Ronald-MultiSafepay** [comment]
@jeroenlammerts

We have created an internal ticket for this issue with ticket-id PLGWOOS-203 and will try to solve this as soon as possible.

On the Wordpress forum there is a workaround available witch might work for you.
https://wpml.org/forums/topic/multisafepay-and-wpml-string-translation-doesnt-work-together/ ?

**Comment by jeroenlammerts** [comment]
I came up with the same workaround as on the wpml forum but this doesn't work for the default language. It shows an empty string for the default language.

**Comment by jeroenlammerts** [comment]
@Ronald-MultiSafepay do you have an update about the status of this issue? Do you know when it will be resolved?

**Comment by Ronald-MultiSafepay** [comment]
@jeroenlammerts  We will investigate this issue within the next two weeks. 
Depending on the results, we will give you a realistic estimation when this can be resolved.

**Comment by jeroenlammerts** [comment]
@Ronald-MultiSafepay is there any update about the status of this issue?

**Comment by Jasper-MultiSafepay** [comment]
@jeroenlammerts 
Investigating of the issue has almost been completed.
We're currently in the process of rewriting on how the form fields are being read to make this compatible with WPML.
I expect to be able to provide you with a patch within 2 weeks

**Comment by Ronald-MultiSafepay** [comment]
@jeroenlammerts
A patch with the fix for WMPL can be found at c75a16e826071b24e17e9a3473831e53cb09636a
We will include this patch in the upcoming version of our plugin.
