### ISSUE TITLE
Betaalmethoden verdwijnen na update 6.x.x

### ISSUE THREAD

**Issue by babaakgol** [MultiSafepay/woocommerce#21]
Alle betaalmethoden opties verwijnen bij het afrekenen /cart. Is dit een bekend probleem?

**Comment by danielcivit** [comment]
Our apologies for not providing an answer before. This ticket was out of our radar somehow. 

It seems, that back in October, 2023, there was an issue related to a new major version of our plugin. In those days, saving the API Key on the settings page of our plugin was required to solve this issue.

Feel free to re-open this ticket if needed. 

Thanks
