### ISSUE TITLE
Option for enable direct bank transfer on payment method 'Bank Transfer' is gone -  MultiSafepay v. 6.3.1 

### ISSUE THREAD

**Issue by ictbollaert** [MultiSafepay/woocommerce#22]
Hi

I noticed that on MultiSafePay v5.3.1 you could enable direct bank transfer which worked great for us (so order confirmed in webshop and customer gets mail from msp system)
![image](https://github.com/MultiSafepay/woocommerce/assets/91456554/640707d9-5f49-490e-81a2-6ba88486a3de)

However, in the new MSP plugin version v. 6.3.1 this option is gone. 
![image](https://github.com/MultiSafepay/woocommerce/assets/91456554/698aa263-6fe0-4fef-b10c-120b94ff47c0)

Is there any MSP plugin version which supports the woocommerce checkout blocks AND has enable direct bank transfer option? 

Or is there a way to activate this? 

WooCommerce Checkout blocks: 
https://woo.com/document/cart-checkout-blocks-status/

When i install MSP v5.3.1 on my new woo shop as a test which is in development i can not use the msp options on the woocommerce checkout blocks 
![image](https://github.com/MultiSafepay/woocommerce/assets/91456554/94d808f8-b19c-4f2a-ae4d-8245d604cf12)

**Comment by danielcivit** [comment]
Hello @ictbollaert 

Thanks for contacting us with your report and feedback.  Following your request, this option will be back in the next release. 
I will contact you via this channel when that is done.
