### ISSUE TITLE
Does this plug-in support the upcoming iDEAL 2.0 release?

### ISSUE THREAD

**Issue by buismaarten** [MultiSafepay/woocommerce#23]

**Comment by danielcivit** [comment]
Hi @buismaarten.

Our apologies for the late response. This ticket was, for some time, out of our radar. 

This plugin will support any payment method available in your MultiSafepay account, including iDEAL 2.0.
Please contact your account manager at MultiSafepay to know the details and see if that payment method is available.

Thanks.
