### ISSUE TITLE
Plugin default installation folder

### ISSUE THREAD

**Issue by crs1138** [MultiSafepay/WooCommerce#3]
I took over a project from one of my clients. He installed the MultiSafepay plugin into the folder `wp-content/plugins/Woocommerce-3.2.0`. What is the correct folder?

**Comment by Jasper-MultiSafepay** [comment]
The correct folder should be `wp-content/plugins/multisafepay`

**Comment by Jasper-MultiSafepay** [comment]
Created PLGWOOS-297 to make this more clear in our manuals
