### ISSUE TITLE
Javascript error Apple pay

### ISSUE THREAD

**Issue by uprise10** [MultiSafepay/WooCommerce#7]
On our install we get a Javascript error on the checkout page in applepay.js since the 3.5.0 version. 

![apple-pay-error](https://user-images.githubusercontent.com/1333461/79438007-41622700-7fd3-11ea-950a-a4a32f78615f.png)

Our Setup:
 - WordPress 5.4
 - WooCommerce 4.0.1
 - Multisafepay 3.5.0

We switched back to 3.4.0 to get it working again.

**Comment by Jasper-MultiSafepay** [comment]
@uprise10 
Thank you for reporting this, we can reproduce this successfully and are working on a fix for this.

**Comment by Jasper-MultiSafepay** [comment]
@uprise10 
This issue has been resolved on our develop branch in https://github.com/MultiSafepay/WooCommerce/commit/66a754475e1f712814656d9fb277025a70b04f41
You can apply the change or wait for the 3.5.1 release (expected somewhere next week)
